# Python stubs generated by omniidl from guard.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Guarda"
#
__name__ = "Guarda"
_0_Guarda = omniORB.openModule("Guarda", r"guard.idl")
_0_Guarda__POA = omniORB.openModule("Guarda__POA", r"guard.idl")


# interface Guard
_0_Guarda._d_Guard = (omniORB.tcInternal.tv_objref, "IDL:Guarda/Guard:1.0", "Guard")
omniORB.typeMapping["IDL:Guarda/Guard:1.0"] = _0_Guarda._d_Guard
_0_Guarda.Guard = omniORB.newEmptyClass()
class Guard :
    _NP_RepositoryId = _0_Guarda._d_Guard[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Guarda.Guard = Guard
_0_Guarda._tc_Guard = omniORB.tcInternal.createTypeCode(_0_Guarda._d_Guard)
omniORB.registerType(Guard._NP_RepositoryId, _0_Guarda._d_Guard, _0_Guarda._tc_Guard)

# Guard operations and attributes
Guard._d_warns_guard = (((omniORB.tcInternal.tv_string,0), ), (), None)
Guard._d_get_visitors = ((), (omniORB.tcInternal.tv_long, ), None)
Guard._d_is_night = ((), (), None)

# Guard object reference
class _objref_Guard (CORBA.Object):
    _NP_RepositoryId = Guard._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def warns_guard(self, *args):
        return self._obj.invoke("warns_guard", _0_Guarda.Guard._d_warns_guard, args)

    def get_visitors(self, *args):
        return self._obj.invoke("get_visitors", _0_Guarda.Guard._d_get_visitors, args)

    def is_night(self, *args):
        return self._obj.invoke("is_night", _0_Guarda.Guard._d_is_night, args)

omniORB.registerObjref(Guard._NP_RepositoryId, _objref_Guard)
_0_Guarda._objref_Guard = _objref_Guard
del Guard, _objref_Guard

# Guard skeleton
__name__ = "Guarda__POA"
class Guard (PortableServer.Servant):
    _NP_RepositoryId = _0_Guarda.Guard._NP_RepositoryId


    _omni_op_d = {"warns_guard": _0_Guarda.Guard._d_warns_guard, "get_visitors": _0_Guarda.Guard._d_get_visitors, "is_night": _0_Guarda.Guard._d_is_night}

Guard._omni_skeleton = Guard
_0_Guarda__POA.Guard = Guard
omniORB.registerSkeleton(Guard._NP_RepositoryId, Guard)
del Guard
__name__ = "Guarda"

#
# End of module "Guarda"
#
__name__ = "guard_idl"

_exported_modules = ( "Guarda", )

# The end.
