# DO NOT EDIT THIS FILE!
#
# Python module Guarda__POA generated by omniidl

import omniORB
omniORB.updateModule("Guarda__POA")

# ** 1. Stub files contributing to this module
import guard_idl

# ** 2. Sub-modules

# ** 3. End
